
[common]

	[common.crafting]
		#enablePropeller
		enablePropeller = true
		#enableHeavyDutyPropeller
		enableHeavyDutyPropeller = true
		#enableTractorWheel
		enableTractorWheel = true
		#enableSportTire
		enableSportTire = true
		#enableJetThruster
		enableJetThruster = true
		#enableAirRudder
		enableAirRudder = true
		#enableBoatRudder
		enableBoatRudder = true
		#enableSubmarineRudder
		enableSubmarineRudder = true
		#enableSteamEngine
		enableSteamEngine = true
		#enableCombustionEngine
		enableCombustionEngine = true
		#enableSiftingNet
		enableSiftingNet = true
		#enableStasisGun
		enableStasisGun = true
		#enableHelicopterRotor
		enableHelicopterRotor = true
		#enableBalloonBlock
		enableBalloonBlock = true
		#enableBoatSail
		enableBoatSail = true
		#enableTeleportationTransponder
		enableTeleportationTransponder = true
		#enablePlatinumBow
		enablePlatinumBow = true
		#enableFluidShippingTank
		enableFluidShippingTank = true
		#enableManipulator
		enableManipulator = true
		#enableAutoCraftingTable
		enableAutoCraftingTable = true
		#enableBlueprintingTable
		enableBlueprintingTable = true

	[common.ship]
		#Distance from windshield when piloting
		#Range: 0.1 ~ 0.8
		pilotingWindshieldDistance = 0.4
		#Max ship block count
		#Range: 5 ~ 1000000
		maxShipBlockCount = 2000
		#Weight multiplier for ship block-weight
		#Range: 0.01 ~ 1000000.0
		weightConversionRatio = 35.0
		#Mover diminishing-returns factor
		#Range: 0.01 ~ 10.0
		moverDiminishingReturns = 0.98
		#Block-weight exponential factor
		#Range: 0.01 ~ 10.0
		blockWeightExponent = 1.15
		#Wooden-block weight multiplier
		#Range: 0.01 ~ 10.0
		woodWeightMultiplier = 0.6
		#Chain block weight multiplier
		#Range: 0.01 ~ 10.0
		chainWeightMultiplier = 0.05
		#useComplexCollision?
		useComplexCollision = true

	[common.ship_building]

		[common.ship_building.mover_horizontal_top_speed]
			#tractorWheelTopSpeedBps
			#Range: 0.01 ~ 1000.0
			tractorWheelTopSpeedBps = 5.0
			#tractorWheelTimeToTopSpeed
			#Range: 0.01 ~ 1000.0
			tractorWheelTimeToTopSpeed = 2.0
			#sportTireTopSpeedBps
			#Range: 0.01 ~ 1000.0
			sportTireTopSpeedBps = 15.0
			#sportTireTimeToTopSpeed
			#Range: 0.01 ~ 1000.0
			sportTireTimeToTopSpeed = 3.5
			#boatSailTopSpeedBps
			#Range: 0.01 ~ 1000.0
			boatSailTopSpeedBps = 10.0
			#boatSailTimeToTopSpeed
			#Range: 0.01 ~ 1000.0
			boatSailTimeToTopSpeed = 9.0
			#balloonTopSpeedBps
			#Range: 0.01 ~ 1000.0
			balloonTopSpeedBps = 4.0
			#balloonTimeToTopSpeed
			#Range: 0.01 ~ 1000.0
			balloonTimeToTopSpeed = 8.0
			#propellerTopSpeedBps
			#Range: 0.01 ~ 1000.0
			propellerTopSpeedBps = 18.0
			#propellerTimeToTopSpeed
			#Range: 0.01 ~ 1000.0
			propellerTimeToTopSpeed = 11.5
			#heavyDutyPropellerTopSpeedBps
			#Range: 0.01 ~ 1000.0
			heavyDutyPropellerTopSpeedBps = 18.0
			#heavyDutyPropellerTimeToTopSpeed
			#Range: 0.01 ~ 1000.0
			heavyDutyPropellerTimeToTopSpeed = 11.5
			#jetThrusterTopSpeedBps
			#Range: 0.01 ~ 1000.0
			jetThrusterTopSpeedBps = 40.0
			#jetThrusterTimeToTopSpeed
			#Range: 0.01 ~ 1000.0
			jetThrusterTimeToTopSpeed = 9.5
			#helicopterRotorTopSpeedBps
			#Range: 0.01 ~ 1000.0
			helicopterRotorTopSpeedBps = 12.0
			#helicopterRotorTimeToTopSpeed
			#Range: 0.01 ~ 1000.0
			helicopterRotorTimeToTopSpeed = 8.0

		[common.ship_building.mover_vertical_top_speed]
			#verticalBalloonTopSpeedBps
			#Range: 0.01 ~ 1000.0
			verticalBalloonTopSpeedBps = 2.0
			#verticalBalloonTimeToTopSpeed
			#Range: 0.01 ~ 1000.0
			verticalBalloonTimeToTopSpeed = 3.5
			#verticalPropellerTopSpeedBps
			#Range: 0.01 ~ 1000.0
			verticalPropellerTopSpeedBps = 5.5
			#verticalPropellerTimeToTopSpeed
			#Range: 0.01 ~ 1000.0
			verticalPropellerTimeToTopSpeed = 3.2
			#verticalHeavyDutyPropellerTopSpeedBps
			#Range: 0.01 ~ 1000.0
			verticalHeavyDutyPropellerTopSpeedBps = 5.5
			#verticalHeavyDutyPropellerTimeToTopSpeed
			#Range: 0.01 ~ 1000.0
			verticalHeavyDutyPropellerTimeToTopSpeed = 3.2
			#verticalJetThrusterTopSpeedBps
			#Range: 0.01 ~ 1000.0
			verticalJetThrusterTopSpeedBps = 11.0
			#verticalJetThrusterTimeToTopSpeed
			#Range: 0.01 ~ 1000.0
			verticalJetThrusterTimeToTopSpeed = 2.2
			#verticalHelicopterRotorTopSpeedBps
			#Range: 0.01 ~ 1000.0
			verticalHelicopterRotorTopSpeedBps = 6.0
			#verticalHelicopterRotorTimeToTopSpeed
			#Range: 0.01 ~ 1000.0
			verticalHelicopterRotorTimeToTopSpeed = 3.0

		[common.ship_building.mover_horizontal_power]
			#tractorWheelTopSpeedBpsPer1000lb
			#Range: 0.01 ~ 1000.0
			tractorWheelTopSpeedBpsPer1000lb = 38.19
			#tractorWheelTimeToTopSpeedPer1000lb
			#Range: 0.01 ~ 1000.0
			tractorWheelTimeToTopSpeedPer1000lb = 13.0
			#sportTireTopSpeedBpsPer1000lb
			#Range: 0.01 ~ 1000.0
			sportTireTopSpeedBpsPer1000lb = 20.0
			#sportTireTimeToTopSpeedPer1000lb
			#Range: 0.01 ~ 1000.0
			sportTireTimeToTopSpeedPer1000lb = 6.0
			#boatSailTopSpeedBpsPer1000lb
			#Range: 0.01 ~ 1000.0
			boatSailTopSpeedBpsPer1000lb = 3.1
			#boatSailTimeToTopSpeedPer1000lb
			#Range: 0.01 ~ 1000.0
			boatSailTimeToTopSpeedPer1000lb = 8.0
			#balloonTopSpeedBpsPer1000lb
			#Range: 0.01 ~ 1000.0
			balloonTopSpeedBpsPer1000lb = 3.1
			#balloonTimeToTopSpeedPer1000lb
			#Range: 0.01 ~ 1000.0
			balloonTimeToTopSpeedPer1000lb = 8.0
			#propellerTopSpeedBpsPer1000lb
			#Range: 0.01 ~ 1000.0
			propellerTopSpeedBpsPer1000lb = 23.9
			#propellerTimeToTopSpeedPer1000lb
			#Range: 0.01 ~ 1000.0
			propellerTimeToTopSpeedPer1000lb = 10.0
			#heavyDutyPropellerTopSpeedBpsPer1000lb
			#Range: 0.01 ~ 1000.0
			heavyDutyPropellerTopSpeedBpsPer1000lb = 75.0
			#heavyDutyPropellerTimeToTopSpeedPer1000lb
			#Range: 0.01 ~ 1000.0
			heavyDutyPropellerTimeToTopSpeedPer1000lb = 10.0
			#jetThrusterTopSpeedBpsPer1000lb
			#Range: 0.01 ~ 1000.0
			jetThrusterTopSpeedBpsPer1000lb = 180.0
			#jetThrusterTimeToTopSpeedPer1000lb
			#Range: 0.01 ~ 1000.0
			jetThrusterTimeToTopSpeedPer1000lb = 10.0
			#helicopterRotorTopSpeedBpsPer1000lb
			#Range: 0.01 ~ 1000.0
			helicopterRotorTopSpeedBpsPer1000lb = 47.74
			#helicopterRotorTimeToTopSpeedPer1000lb
			#Range: 0.01 ~ 1000.0
			helicopterRotorTimeToTopSpeedPer1000lb = 11.75

		[common.ship_building.mover_vertical_power]
			#verticalBalloonTopSpeedBpsPer1000lb
			#Range: 0.01 ~ 1000.0
			verticalBalloonTopSpeedBpsPer1000lb = 2.39
			#verticalBalloonTimeToTopSpeedPer1000lb
			#Range: 0.01 ~ 1000.0
			verticalBalloonTimeToTopSpeedPer1000lb = 3.0
			#verticalPropellerTopSpeedBpsPer1000lb
			#Range: 0.01 ~ 1000.0
			verticalPropellerTopSpeedBpsPer1000lb = 7.16
			#verticalPropellerTimeToTopSpeedPer1000lb
			#Range: 0.01 ~ 1000.0
			verticalPropellerTimeToTopSpeedPer1000lb = 2.0
			#verticalHeavyDutyPropellerTopSpeedBpsPer1000lb
			#Range: 0.01 ~ 1000.0
			verticalHeavyDutyPropellerTopSpeedBpsPer1000lb = 23.0
			#verticalHeavyDutyPropellerTimeToTopSpeedPer1000lb
			#Range: 0.01 ~ 1000.0
			verticalHeavyDutyPropellerTimeToTopSpeedPer1000lb = 2.0
			#verticalJetThrusterTopSpeedBpsPer1000lb
			#Range: 0.01 ~ 1000.0
			verticalJetThrusterTopSpeedBpsPer1000lb = 56.0
			#verticalJetThrusterTimeToTopSpeedPer1000lb
			#Range: 0.01 ~ 1000.0
			verticalJetThrusterTimeToTopSpeedPer1000lb = 2.4
			#verticalHelicopterRotorTopSpeedBpsPer1000lb
			#Range: 0.01 ~ 1000.0
			verticalHelicopterRotorTopSpeedBpsPer1000lb = 42.97
			#verticalHelicopterRotorTimeToTopSpeedPer1000lb
			#Range: 0.01 ~ 1000.0
			verticalHelicopterRotorTimeToTopSpeedPer1000lb = 3.0

		[common.ship_building.submarine_modifiers]
			#submarineTopSpeedModifier
			#Range: 0.01 ~ 1000.0
			submarineTopSpeedModifier = 0.7
			#submarineAccelerationModifier
			#Range: 0.01 ~ 1000.0
			submarineAccelerationModifier = 0.7

