
[[mobSetConfiguration]]

	# example2
	[[mobSetConfiguration.mobSets]]
		name = "treasure2:wishing_well_group"
		category = "wishing_wells"
		biomeWhitelist = []
		biomeBlacklist = []

		[mobSetConfiguration.mobSets.count]
			min = 1
			max = 3

		[[mobSetConfiguration.mobSets.mobs]]
			name = "minecraft:zombie"
			weight = 35

		[[mobSetConfiguration.mobSets.mobs]]
			name = "minecraft:zombie_villager"
			weight = 10

		[[mobSetConfiguration.mobSets.mobs]]
			name = "minecraft:skeleton"
			weight = 35

		[[mobSetConfiguration.mobSets.mobs]]
			name = "minecraft:vex"
			weight = 20

		[[mobSetConfiguration.mobSets.mobs]]
			name = "minecraft:creeper"
			weight = 15

		[[mobSetConfiguration.mobSets.mobs]]
			name = "minecraft:slime"
			weight = 5

	[[mobSetConfiguration.mobSets]]
		name = "treasure2:small_zombie_group"
		category = "zombies"
		biomeWhitelist = []
		biomeBlacklist = []

		[mobSetConfiguration.mobSets.count]
			min = 1
			max = 3

		[[mobSetConfiguration.mobSets.mobs]]
			name = "minecraft:zombie"
			weight = 90

		[[mobSetConfiguration.mobSets.mobs]]
			name = "minecraft:zombie_villager"
			weight = 10

	[[mobSetConfiguration.mobSets]]
		name = "treasure2:medium_zombie_group"
		category = "zombies"
		biomeWhitelist = []
		biomeBlacklist = []

		[mobSetConfiguration.mobSets.count]
			min = 2
			max = 5

		[[mobSetConfiguration.mobSets.mobs]]
			name = "minecraft:zombie"
			weight = 90

		[[mobSetConfiguration.mobSets.mobs]]
			name = "minecraft:zombie_villager"
			weight = 10

